hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/mental_health_therapy_center?createDatabaseIfNotExist=true
hibernate.connection.username=mysql
hibernate.connection.password=1234

hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

hibernate.show_sql=true
hibernate.format_sql=true

hibernate.hbm2ddl.auto=update